#include <feature_extraction/colors.hpp>

#define COLOR_SHADES_MAX 15

// white 
#define NUMBER_OF_WHITE 32
const Color white_shades[] = {
  COLOR_ALICE_BLUE,
  COLOR_ANTIQUE_WHITE,
  COLOR_AZURE_MIST,
  COLOR_AZURE_WEB_COLOR,
  COLOR_BABY_POWDER,
  COLOR_BEIGE,
  COLOR_BONE,
  COLOR_CHAMPAGNE,
  COLOR_CORNSILK,
  COLOR_CREAM,
  COLOR_CULTURED,
  COLOR_DUTCH_WHITE,
  COLOR_ECRU,
  COLOR_EGGSHELL,
  COLOR_FLAX,
  COLOR_FLORAL_WHITE,
  COLOR_GHOST_WHITE,
  COLOR_HONEYDEW,
  COLOR_IVORY,
  COLOR_LAVENDER_BLUSH,
  COLOR_LINEN,
  COLOR_MEDIUM_CHAMPAGNE,
  COLOR_MINT_CREAM,
  COLOR_MOCCASIN,
  COLOR_NAVAJO_WHITE,
  COLOR_OLD_LACE,
  COLOR_SAND,
  COLOR_SEASHELL,
  COLOR_SNOW,
  COLOR_VANILLA,
  COLOR_WHITE,
  COLOR_WHITE_SMOKE
};

// gray 
#define NUMBER_OF_GRAY 37
const Color gray_shades[] = {
  COLOR_ASH_GREY,
  COLOR_BATTLESHIP_GREY,
  COLOR_BLUE_GRAY,
  COLOR_CADET_GREY,
  COLOR_CHARCOAL,
  COLOR_CINEREOUS,
  COLOR_COOL_GREY,
  COLOR_DARK_GRAY_X11,
  COLOR_DARK_LAVA,
  COLOR_DARK_MEDIUM_GRAY,
  COLOR_DARK_SLATE_GRAY,
  COLOR_DARK_TAUPE,
  COLOR_DAVY_S_GREY,
  COLOR_DIM_GRAY,
  COLOR_DUST_STORM,
  COLOR_GAINSBORO,
  COLOR_GLAUCOUS,
  COLOR_GRAY,
  COLOR_GRAY_BLUE,
  COLOR_GRAY_HTML_CSS_GRAY,
  COLOR_GRAY_X11_GRAY,
  COLOR_GUNMETAL,
  COLOR_HELIOTROPE_GRAY,
  COLOR_JET,
  COLOR_LIGHT_GRAY,
  COLOR_LIGHT_SLATE_GRAY,
  COLOR_LIVID,
  COLOR_NICKEL,
  COLOR_OLD_SILVER,
  COLOR_PLATINUM,
  COLOR_ROCKET_METALLIC,
  COLOR_ROSE_QUARTZ,
  COLOR_SILVER,
  COLOR_SLATE_GRAY,
  COLOR_SPANISH_GRAY,
  COLOR_TAUPE,
  COLOR_TROLLEY_GREY
};

// black 
#define NUMBER_OF_BLACK 21
const Color black_shades[] = {
  COLOR_BLACK,
  COLOR_BLACK_BEAN,
  COLOR_BLACK_LEATHER_JACKET,
  COLOR_BLACK_OLIVE,
  COLOR_CAF_NOIR,
  COLOR_CHARCOAL,
  COLOR_CHARLESTON_GREEN,
  COLOR_DARK_LAVA,
  COLOR_DARK_TAUPE,
  COLOR_DAVY_S_GREY,
  COLOR_DIM_GRAY,
  COLOR_EBONY,
  COLOR_EERIE_BLACK,
  COLOR_JET,
  COLOR_LICORICE,
  COLOR_MIDNIGHT_BLUE,
  COLOR_ONYX,
  COLOR_OUTER_SPACE,
  COLOR_PHTHALO_GREEN,
  COLOR_RAISIN_BLACK,
  COLOR_TAUPE
};

// magenta 
#define NUMBER_OF_MAGENTA 23
const Color magenta_shades[] = {
  COLOR_AMARANTH_PURPLE,
  COLOR_DARK_MAGENTA,
  COLOR_FUCHSIA,
  COLOR_HOT_MAGENTA,
  COLOR_LIGHT_GRAYISH_MAGENTA,
  COLOR_MAGENTA,
  COLOR_MAGENTA_CRAYOLA,
  COLOR_MAGENTA_DYE,
  COLOR_MAGENTA_HAZE,
  COLOR_MAGENTA_PANTONE,
  COLOR_MAGENTA_PROCESS,
  COLOR_ORCHID,
  COLOR_PALE_MAGENTA,
  COLOR_PLUM,
  COLOR_PURPLE_PIZZAZZ,
  COLOR_QUINACRIDONE_MAGENTA,
  COLOR_RAZZLE_DAZZLE_ROSE,
  COLOR_SHOCKING_PINK,
  COLOR_SHOCKING_PINK_CRAYOLA,
  COLOR_SKY_MAGENTA,
  COLOR_STEEL_PINK,
  COLOR_TELEMAGENTA,
  COLOR_ULTRA_PINK
};

// pink 
#define NUMBER_OF_PINK 57
const Color pink_shades[] = {
  COLOR_AMARANTH_PINK,
  COLOR_BABY_PINK,
  COLOR_BAKER_MILLER_PINK,
  COLOR_BARBIE_PINK,
  COLOR_BRIGHT_PINK,
  COLOR_BRINK_PINK,
  COLOR_CAMEO_PINK,
  COLOR_CANDY_PINK,
  COLOR_CARNATION_PINK,
  COLOR_CHAMPAGNE_PINK,
  COLOR_CHARM_PINK,
  COLOR_CHERRY_BLOSSOM_PINK,
  COLOR_CHINA_PINK,
  COLOR_CONGO_PINK,
  COLOR_CORAL_PINK,
  COLOR_COTTON_CANDY,
  COLOR_DARK_PINK,
  COLOR_DEEP_PINK,
  COLOR_FANDANGO_PINK,
  COLOR_FLUORESCENT_PINK,
  COLOR_FRENCH_PINK,
  COLOR_HOT_PINK,
  COLOR_LAVENDER_PINK,
  COLOR_LIGHT_DEEP_PINK,
  COLOR_LIGHT_HOT_PINK,
  COLOR_LIGHT_PINK,
  COLOR_LIGHT_THULIAN_PINK,
  COLOR_LISERAN_PURPLE,
  COLOR_MEXICAN_PINK,
  COLOR_MIMI_PINK,
  COLOR_MOUNTBATTEN_PINK,
  COLOR_NEW_YORK_PINK,
  COLOR_ORCHID_PINK,
  COLOR_PALE_PINK,
  COLOR_PARADISE_PINK,
  COLOR_PASTEL_PINK,
  COLOR_PERSIAN_PINK,
  COLOR_PIGGY_PINK,
  COLOR_PINK,
  COLOR_PINK_LACE,
  COLOR_PINK_LAVENDER,
  COLOR_PINK_PANTONE,
  COLOR_QUEEN_PINK,
  COLOR_ROSE,
  COLOR_SCHAUSS_PINK,
  COLOR_SHOCKING_PINK,
  COLOR_SHOCKING_PINK_CRAYOLA,
  COLOR_SILVER_PINK,
  COLOR_SOLID_PINK,
  COLOR_SPANISH_PINK,
  COLOR_STEEL_PINK,
  COLOR_SUPER_PINK,
  COLOR_TANGO_PINK,
  COLOR_TEA_ROSE,
  COLOR_THULIAN_PINK,
  COLOR_TICKLE_ME_PINK,
  COLOR_ULTRA_PINK
};

// red (low)
#define NUMBER_OF_RED_LOW 26
const Color red_low_shades[] = {
  COLOR_BARN_RED, // Low
  COLOR_CARNELIAN, // Low
  COLOR_CINNABAR,  // Low
  COLOR_CONGO_PINK, // Low
  COLOR_CORAL_PINK, // Low
  COLOR_CORAL_RED, // Low
  COLOR_CORNELL_RED, // Low
  COLOR_CRIMSON_RED, // Low
  COLOR_DARK_PASTEL_RED, // Low
  COLOR_DARK_RED, // Low
  COLOR_FIREBRICK, // Low
  COLOR_INDIAN_RED, // Low
  COLOR_LUST, // Low
  COLOR_MAHOGANY, // Low
  COLOR_MAROON_HTML_CSS, // Low
  COLOR_MAXIMUM_RED, // Low
  COLOR_MIDDLE_RED, // Low
  COLOR_MIDDLE_RED_PURPLE,  // Low
  COLOR_OU_CRIMSON_RED, // Low
  COLOR_PASTEL_RED, // Low
  COLOR_RED, // Low
  COLOR_REDWOOD, // Low
  COLOR_SALMON, // Low
  COLOR_STIZZA, // Low
  COLOR_TERRA_COTTA, // Low
  COLOR_USC_CARDINAL // Low
};

// red (high) 
#define NUMBER_OF_RED_HIGH 24
const Color red_high_shades[] = {
  COLOR_AWESOME, // High
  COLOR_CARDINAL, // High
  COLOR_CARMINE, // High
  COLOR_CRIMSON, // High
  COLOR_DESIRE, // High
  COLOR_FIRE_ENGINE_RED, // High
  COLOR_HEIDELBERG_RED, // High
  COLOR_IMPERIAL_RED, // High
  COLOR_LAVA, // High
  COLOR_MAXIMUM_RED_PURPLE, // High
  COLOR_PINK, // High
  COLOR_RED_CRAYOLA, // High
  COLOR_RED_MUNSELL, // High
  COLOR_RED_NCS, // High
  COLOR_RED_PANTONE, // High
  COLOR_RED_PIGMENT, // High
  COLOR_ROSEWOOD, // High
  COLOR_RUBY, // High
  COLOR_RUBY_RED, // High
  COLOR_RUSTY_RED, // High
  COLOR_SPANISH_RED, // High
  COLOR_VENETIAN_RED, // High
  COLOR_VIVID_RED, // High
  COLOR_WINE // High
};

 // brown 
#define NUMBER_OF_BROWN 56
const Color brown_shades[] = {
  COLOR_ANTIQUE_BRONZE,
  COLOR_AUBURN,
  COLOR_BEAVER,
  COLOR_BEIGE,
  COLOR_BISTRE,
  COLOR_BISTRE_BROWN,
  COLOR_BOLE,
  COLOR_BRONZE,
  COLOR_BROWN_NOSE,
  COLOR_BROWN_WEB,
  COLOR_BUFF,
  COLOR_BURNT_UMBER,
  COLOR_CAF_AU_LAIT,
  COLOR_CAMEL,
  COLOR_CHESTNUT,
  COLOR_CHOCOLATE_TRADITIONAL,
  COLOR_CHOCOLATE_WEB,
  COLOR_CINNAMON,
  COLOR_COCOA_BROWN,
  COLOR_DARK_BROWN,
  COLOR_DARK_BROWN_TANGELO,
  COLOR_DARK_LAVA,
  COLOR_DARK_TAUPE,
  COLOR_DEER,
  COLOR_DESERT,
  COLOR_DESERT_SAND,
  COLOR_DONKEY_BROWN,
  COLOR_DRAB,
  COLOR_FALLOW,
  COLOR_FLATTERY,
  COLOR_FRENCH_BEIGE,
  COLOR_FRENCH_BISTRE,
  COLOR_GOLDEN_BROWN,
  COLOR_KHAKI_HTML_CSS_KHAKI,
  COLOR_KOBICHA,
  COLOR_MAHOGANY,
  COLOR_MEDIUM_TUSCAN_RED,
  COLOR_MODE_BEIGE,
  COLOR_OCHRE,
  COLOR_PERU,
  COLOR_RAW_UMBER,
  COLOR_RED_BROWN,
  COLOR_ROSY_BROWN,
  COLOR_RUSSET,
  COLOR_SANDY_BROWN,
  COLOR_SANDY_TAUPE,
  COLOR_SAND_DUNE,
  COLOR_SATIN_SHEEN_GOLD,
  COLOR_SEAL_BROWN,
  COLOR_SEPIA,
  COLOR_SMOKEY_TOPAZ,
  COLOR_TAN,
  COLOR_TAUPE,
  COLOR_TENN_TAWNY,
  COLOR_TUSCAN_TAN,
  COLOR_WOOD_BROWN
};

// orange 
#define NUMBER_OF_ORANGE 45
const Color orange_shades[] = {
  COLOR_ALLOY_ORANGE,
  COLOR_APRICOT,
  COLOR_ATOMIC_TANGERINE,
  COLOR_BITTERSWEET,
  COLOR_BITTERSWEET_SHIMMER,
  COLOR_BROWN_TRADITIONAL,
  COLOR_BURNT_ORANGE,
  COLOR_CARROT_ORANGE,
  COLOR_CINNABAR,
  COLOR_CONGO_PINK,
  COLOR_CORAL,
  COLOR_CORAL_PINK,
  COLOR_DARK_ORANGE,
  COLOR_DARK_TANGERINE,
  COLOR_DEEP_CARROT_ORANGE,
  COLOR_GAMBOGE,
  COLOR_GIANTS_ORANGE,
  COLOR_GOLD_METALLIC,
  COLOR_INTERNATIONAL_ORANGE_AEROSPACE,
  COLOR_INTERNATIONAL_ORANGE_ENGINEERING,
  COLOR_LIGHT_ORANGE,
  COLOR_MELON,
  COLOR_MIDDLE_YELLOW_RED,
  COLOR_ORANGE_COLOR_WHEEL,
  COLOR_ORANGE_CRAYOLA,
  COLOR_ORANGE_PANTONE,
  COLOR_ORANGE_PEEL,
  COLOR_ORANGE_WEB,
  COLOR_ORIOLES_ORANGE,
  COLOR_PAPAYA_WHIP,
  COLOR_PERSIAN_ORANGE,
  COLOR_PERSIMMON,
  COLOR_PINK_ORANGE,
  COLOR_PORTLAND_ORANGE,
  COLOR_PRINCETON_ORANGE,
  COLOR_PUMPKIN,
  COLOR_SPANISH_ORANGE,
  COLOR_TANGELO,
  COLOR_TEA_ROSE,
  COLOR_TENN_TAWNY,
  COLOR_TOMATO,
  COLOR_VERY_PALE_ORANGE,
  COLOR_VIVID_ORANGE,
  COLOR_VIVID_ORANGE_PEEL,
  COLOR_WILLPOWER_ORANGE
};

// yellow 
#define NUMBER_OF_YELLOW 53
const Color yellow_shades[] = {
  COLOR_ARYLIDE_YELLOW,
  COLOR_AUREOLIN,
  COLOR_BANANA_YELLOW,
  COLOR_BUFF,
  COLOR_CANARY_YELLOW,
  COLOR_CHARTREUSE_TRADITIONAL,
  COLOR_CITRINE,
  COLOR_CYBER_YELLOW,
  COLOR_DAFFODIL,
  COLOR_DANDELION,
  COLOR_ELECTRIC_YELLOW,
  COLOR_GOLDENROD,
  COLOR_GOLDEN_POPPY,
  COLOR_GOLDEN_YELLOW,
  COLOR_GOLD_METALLIC,
  COLOR_GOLD_WEB_GOLDEN,
  COLOR_HANSA_YELLOW,
  COLOR_HEART_GOLD,
  COLOR_JASMINE,
  COLOR_JONQUIL,
  COLOR_KHAKI_HTML_CSS_KHAKI,
  COLOR_LASER_LEMON,
  COLOR_LEMON_CHIFFON,
  COLOR_LEMON_GLACIER,
  COLOR_LIGHT_YELLOW,
  COLOR_MAXIMUM_YELLOW,
  COLOR_MELLOW_YELLOW,
  COLOR_MIDDLE_YELLOW,
  COLOR_MUSTARD,
  COLOR_NAPLES_YELLOW,
  COLOR_OLD_GOLD,
  COLOR_OLIVE,
  COLOR_PASTEL_YELLOW,
  COLOR_ROYAL_YELLOW,
  COLOR_SAFETY_YELLOW,
  COLOR_SAFFRON,
  COLOR_SCHOOL_BUS_YELLOW,
  COLOR_SELECTIVE_YELLOW,
  COLOR_STIL_DE_GRAIN_YELLOW,
  COLOR_STRAW,
  COLOR_SUNGLOW,
  COLOR_TANGERINE_YELLOW,
  COLOR_UNMELLOW_YELLOW,
  COLOR_USC_GOLD,
  COLOR_VERY_PALE_YELLOW,
  COLOR_VIVID_YELLOW,
  COLOR_YELLOW,
  COLOR_YELLOW_CRAYOLA,
  COLOR_YELLOW_MUNSELL,
  COLOR_YELLOW_NCS,
  COLOR_YELLOW_PANTONE,
  COLOR_YELLOW_PROCESS,
  COLOR_YELLOW_ROSE
};

// green 
#define NUMBER_OF_GREEN 80
const Color green_shades[] = {
  COLOR_AO_ENGLISH,
  COLOR_ARMY_GREEN,
  COLOR_ARTICHOKE,
  COLOR_ASPARAGUS,
  COLOR_AVOCADO,
  COLOR_BANGLADESH_GREEN,
  COLOR_BOTTLE_GREEN,
  COLOR_BRIGHT_GREEN,
  COLOR_BRUNSWICK_GREEN,
  COLOR_CAL_POLY_POMONA_GREEN,
  COLOR_CASTLETON_GREEN,
  COLOR_CELADON,
  COLOR_CELADON_GREEN,
  COLOR_DARK_GREEN,
  COLOR_DARK_GREEN_X11,
  COLOR_DARK_MOSS_GREEN,
  COLOR_DARK_PASTEL_GREEN,
  COLOR_DARTMOUTH_GREEN,
  COLOR_DEEP_MOSS_GREEN,
  COLOR_ELECTRIC_GREEN,
  COLOR_EMERALD,
  COLOR_ENGLISH_GREEN,
  COLOR_FELDGRAU,
  COLOR_FERN_GREEN,
  COLOR_FOREST_GREEN_TRADITIONAL,
  COLOR_FOREST_GREEN_WEB,
  COLOR_GO_GREEN,
  COLOR_GRAY_ASPARAGUS,
  COLOR_GREEN_COLOR_WHEEL_X11_GREEN,
  COLOR_GREEN_CRAYOLA,
  COLOR_GREEN_HTML_CSS_COLOR,
  COLOR_GREEN_MUNSELL,
  COLOR_GREEN_NCS,
  COLOR_GREEN_PANTONE,
  COLOR_GREEN_PIGMENT,
  COLOR_GREEN_YELLOW,
  COLOR_HARLEQUIN,
  COLOR_HARLEQUIN_GREEN,
  COLOR_HEART_GOLD,
  COLOR_HOOKER_S_GREEN,
  COLOR_HUNTER_GREEN,
  COLOR_IGUANA_GREEN,
  COLOR_INDIA_GREEN,
  COLOR_ISLAMIC_GREEN,
  COLOR_JADE,
  COLOR_JUNGLE_GREEN,
  COLOR_KELLY_GREEN,
  COLOR_LAUREL_GREEN,
  COLOR_LIGHT_GREEN,
  COLOR_LIME_WEB_X11_GREEN,
  COLOR_MALACHITE,
  COLOR_MANTIS,
  COLOR_MIDDLE_GREEN,
  COLOR_MIDDLE_GREEN_YELLOW,
  COLOR_MIDNIGHT_GREEN_EAGLE_GREEN,
  COLOR_MOSS_GREEN,
  COLOR_MSU_GREEN,
  COLOR_MYRTLE_GREEN,
  COLOR_NEON_GREEN,
  COLOR_OFFICE_GREEN,
  COLOR_OLD_MOSS_GREEN,
  COLOR_OLIVE,
  COLOR_OLIVE_DRAB_3,
  COLOR_OLIVINE,
  COLOR_PAKISTAN_GREEN,
  COLOR_PALE_GREEN,
  COLOR_PARIS_GREEN,
  COLOR_PERSIAN_GREEN,
  COLOR_PINE_GREEN,
  COLOR_RIFLE_GREEN,
  COLOR_RUSSIAN_GREEN,
  COLOR_SACRAMENTO_STATE_GREEN,
  COLOR_SAP_GREEN,
  COLOR_SEA_GREEN,
  COLOR_SHAMROCK_GREEN,
  COLOR_SPANISH_GREEN,
  COLOR_TEAL,
  COLOR_TEA_GREEN,
  COLOR_TURTLE_GREEN,
  COLOR_UP_FOREST_GREEN
};

// cyan 
#define NUMBER_OF_CYAN 35
const Color cyan_shades[] = {
  COLOR_AERO_BLUE,
  COLOR_AQUA,
  COLOR_AQUAMARINE,
  COLOR_BLUE_GREEN,
  COLOR_CELADON_BLUE,
  COLOR_CELESTE,
  COLOR_CERULEAN,
  COLOR_CHARLESTON_GREEN,
  COLOR_CYAN,
  COLOR_CYAN_AZURE,
  COLOR_CYAN_BLUE_AZURE,
  COLOR_CYAN_COBALT_BLUE,
  COLOR_CYAN_CORNFLOWER_BLUE,
  COLOR_CYAN_PROCESS,
  COLOR_DARK_CYAN,
  COLOR_DEEP_AQUAMARINE,
  COLOR_DEEP_GREEN_CYAN_TURQUOISE,
  COLOR_DESATURATED_CYAN,
  COLOR_ELECTRIC_BLUE,
  COLOR_ELECTRIC_CYAN,
  COLOR_GREEN_BLUE,
  COLOR_GREEN_CYAN,
  COLOR_ITALIAN_SKY_BLUE,
  COLOR_KEPPEL,
  COLOR_LIGHT_CYAN,
  COLOR_LIGHT_SEA_GREEN,
  COLOR_MEDIUM_SKY_BLUE,
  COLOR_MIDDLE_BLUE_GREEN,
  COLOR_MIDNIGHT_GREEN_EAGLE_GREEN,
  COLOR_ROBIN_EGG_BLUE,
  COLOR_SPANISH_SKY_BLUE,
  COLOR_TEAL,
  COLOR_TURQUOISE,
  COLOR_VERDIGRIS,
  COLOR_VIRIDIAN
};

// blue 
#define NUMBER_OF_BLUE 89
const Color blue_shades[] = {
  COLOR_AERO,
  COLOR_AIR_FORCE_BLUE_RAF,
  COLOR_AIR_FORCE_BLUE_USAF,
  COLOR_AIR_SUPERIORITY_BLUE,
  COLOR_ALICE_BLUE,
  COLOR_AZURE,
  COLOR_AZURE_MIST,
  COLOR_AZURE_WEB_COLOR,
  COLOR_BABY_BLUE,
  COLOR_BLEU_DE_FRANCE,
  COLOR_BLUE,
  COLOR_BLUE_CRAYOLA,
  COLOR_BLUE_MUNSELL,
  COLOR_BLUE_NCS,
  COLOR_BLUE_PANTONE,
  COLOR_BLUE_PIGMENT,
  COLOR_BLUE_SAPPHIRE,
  COLOR_BLUE_YONDER,
  COLOR_BRANDEIS_BLUE,
  COLOR_BRIGHT_NAVY_BLUE,
  COLOR_B_DAZZLED_BLUE,
  COLOR_CAPRI,
  COLOR_CATALINA_BLUE,
  COLOR_CEIL,
  COLOR_CELADON_BLUE,
  COLOR_CELESTIAL_BLUE,
  COLOR_CERULEAN,
  COLOR_COBALT_BLUE,
  COLOR_CORNFLOWER_BLUE,
  COLOR_DARK_BLUE,
  COLOR_DARK_MIDNIGHT_BLUE,
  COLOR_DARK_PASTEL_BLUE,
  COLOR_DARK_SKY_BLUE,
  COLOR_DEEP_SKY_BLUE,
  COLOR_DIAMOND,
  COLOR_DODGER_BLUE,
  COLOR_EGYPTIAN_BLUE,
  COLOR_ELECTRIC_ULTRAMARINE,
  COLOR_ETON_BLUE,
  COLOR_FRENCH_BLUE,
  COLOR_FRENCH_SKY_BLUE,
  COLOR_GLAUCOUS,
  COLOR_HONOLULU_BLUE,
  COLOR_INDEPENDENCE,
  COLOR_INDIGO_DYE,
  COLOR_JORDY_BLUE,
  COLOR_LAPIS_LAZULI,
  COLOR_LAVENDER_BLUE,
  COLOR_LIBERTY,
  COLOR_LIGHT_BLUE,
  COLOR_LIGHT_CORNFLOWER_BLUE,
  COLOR_LIGHT_SKY_BLUE,
  COLOR_LIGHT_STEEL_BLUE,
  COLOR_MAYA_BLUE,
  COLOR_MEDIUM_BLUE,
  COLOR_MEDIUM_PERSIAN_BLUE,
  COLOR_MEDIUM_SKY_BLUE,
  COLOR_MIDDLE_BLUE,
  COLOR_MIDNIGHT_BLUE,
  COLOR_MORNING_BLUE,
  COLOR_NAVY,
  COLOR_NON_PHOTO_BLUE,
  COLOR_OXFORD_BLUE,
  COLOR_PERIWINKLE,
  COLOR_PERSIAN_BLUE,
  COLOR_PHTHALO_BLUE,
  COLOR_PICTON_BLUE,
  COLOR_POWDER_BLUE,
  COLOR_QUEEN_BLUE,
  COLOR_RACKLEY,
  COLOR_RESOLUTION_BLUE,
  COLOR_ROYAL_BLUE,
  COLOR_SAPPHIRE,
  COLOR_SAPPHIRE_BLUE,
  COLOR_SEA_BLUE,
  COLOR_SILVER_LAKE_BLUE,
  COLOR_SKY_BLUE,
  COLOR_SPACE_CADET,
  COLOR_SPANISH_BLUE,
  COLOR_STEEL_BLUE,
  COLOR_TRUE_BLUE,
  COLOR_TUFTS_BLUE,
  COLOR_ULTRAMARINE,
  COLOR_USAFA_BLUE,
  COLOR_VISTA_BLUE,
  COLOR_VIVID_SKY_BLUE,
  COLOR_WILD_BLUE_YONDER,
  COLOR_YANKEES_BLUE,
  COLOR_ZAFFRE
};

// violet 
#define NUMBER_OF_VIOLET 20
const Color violet_shades[] = {
  COLOR_AFRICAN_VIOLET,
  COLOR_CHINESE_VIOLET,
  COLOR_DARK_VIOLET,
  COLOR_ELECTRIC_VIOLET,
  COLOR_ENGLISH_VIOLET,
  COLOR_FRENCH_VIOLET,
  COLOR_GRAPE,
  COLOR_JAPANESE_VIOLET,
  COLOR_LAVENDER_FLORAL,
  COLOR_LAVENDER_MAGENTA,
  COLOR_MAUVE,
  COLOR_OLD_HELIOTROPE,
  COLOR_PALE_VIOLET,
  COLOR_PINEAPPLE,
  COLOR_RUSSIAN_VIOLET,
  COLOR_SPANISH_VIOLET,
  COLOR_VIOLET,
  COLOR_VIOLET_COLOR_WHEEL,
  COLOR_VIOLET_WEB,
  COLOR_VIVID_VIOLET
};

// purple 
#define NUMBER_OF_PURPLE 39
const Color purple_shades[] = {
  COLOR_BYZANTIUM,
  COLOR_CHINA_PINK,
  COLOR_DARK_PASTEL_PURPLE,
  COLOR_DARK_PURPLE,
  COLOR_ELECTRIC_PURPLE,
  COLOR_EMINENCE,
  COLOR_FRENCH_LILAC,
  COLOR_HELIOTROPE,
  COLOR_IMPERIAL_PURPLE,
  COLOR_KSU_PURPLE,
  COLOR_LISERAN_PURPLE,
  COLOR_MARDI_GRAS,
  COLOR_MAUVE,
  COLOR_MEDIUM_PURPLE,
  COLOR_MEDIUM_VIOLET_RED,
  COLOR_MIDDLE_BLUE_PURPLE,
  COLOR_MIDDLE_PURPLE,
  COLOR_MULBERRY,
  COLOR_ORCHID,
  COLOR_PALATINATE_PURPLE,
  COLOR_PANSY_PURPLE,
  COLOR_PATRIARCH,
  COLOR_PEARLY_PURPLE,
  COLOR_PERSIAN_INDIGO,
  COLOR_PHLOX,
  COLOR_POMP_AND_POWER,
  COLOR_PSYCHEDELIC_PURPLE,
  COLOR_PURPLE_HTML,
  COLOR_PURPLE_MUNSELL,
  COLOR_PURPLE_NAVY,
  COLOR_PURPLE_PIZZAZZ,
  COLOR_PURPLE_X11,
  COLOR_PURPUREUS,
  COLOR_RED_VIOLET,
  COLOR_ROYAL_PURPLE,
  COLOR_THISTLE,
  COLOR_THULIAN_PINK,
  COLOR_TYRIAN_PURPLE,
  COLOR_VERONICA
};

// -----------------------

// Enums and lists
typedef enum ColorShades {
  SHADES_OF_WHITE=0,
  SHADES_OF_GRAY,
  SHADES_OF_BLACK,
  SHADES_OF_MAGENTA,
  SHADES_OF_PINK,
  SHADES_OF_RED_LOW,
  SHADES_OF_RED_HIGH,
  SHADES_OF_BROWN,
  SHADES_OF_ORANGE,
  SHADES_OF_YELLOW,
  SHADES_OF_GREEN,
  SHADES_OF_CYAN,
  SHADES_OF_BLUE,
  SHADES_OF_VIOLET,
  SHADES_OF_PURPLE
} ColorShades;

const int color_shade_numbers[COLOR_SHADES_MAX] = { 
  NUMBER_OF_WHITE,
  NUMBER_OF_GRAY,
  NUMBER_OF_BLACK,
  NUMBER_OF_MAGENTA,
  NUMBER_OF_PINK,
  NUMBER_OF_RED_LOW,
  NUMBER_OF_RED_HIGH,
  NUMBER_OF_BROWN,
  NUMBER_OF_ORANGE,
  NUMBER_OF_YELLOW,
  NUMBER_OF_GREEN,
  NUMBER_OF_CYAN,
  NUMBER_OF_BLUE,
  NUMBER_OF_VIOLET,
  NUMBER_OF_PURPLE
};

const std::string color_shade_names[COLOR_SHADES_MAX] = { 
  "white", 
  "gray", 
  "black", 
  "magenta", 
  "pink", 
  "red", 
  "red", 
  "brown", 
  "orange", 
  "yellow", 
  "green", 
  "cyan", 
  "blue", 
  "violet",
  "purple"
}; 
