string text
anchor_msgs/Anchor[] anchors
anchor_msgs/AnchorLabelConfiguration[] anchor_label_configurations
---
string instruction
anchor_msgs/AnchorLabelConfigurationProbs[] anchor_label_configurations_prob
